//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S1.L03C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S1.L03C.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medellön:{0, 17:c0}.
        /// </summary>
        internal static string Average_Salary {
            get {
                return ResourceManager.GetString("Average_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godtyckling Lönerevision - Nivå C.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tryck tangent för ny beräkning - Esc avslutar..
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! &apos;{0}&apos; är ett för stort tal!.
        /// </summary>
        internal static string High_Number_Error {
            get {
                return ResourceManager.GetString("High_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medianlön:{0, 16:c0}.
        /// </summary>
        internal static string Median_Salary {
            get {
                return ResourceManager.GetString("Median_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! &apos;{0}&apos; kan inte tolkas som ett heltal!.
        /// </summary>
        internal static string Number_Error {
            get {
                return ResourceManager.GetString("Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slut på minne, {0} är ett för stort tal för din dator, provar {1} istället!.
        /// </summary>
        internal static string OutOfMemory_Error {
            get {
                return ResourceManager.GetString("OutOfMemory_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------.
        /// </summary>
        internal static string Result_Line {
            get {
                return ResourceManager.GetString("Result_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste mata in minst två löner för att kunna göra en beräkning!.
        /// </summary>
        internal static string Salary_Number_Error {
            get {
                return ResourceManager.GetString("Salary_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange lön nummer {0}: .
        /// </summary>
        internal static string Salary_Number_Prompt {
            get {
                return ResourceManager.GetString("Salary_Number_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange antal löner att mata in: .
        /// </summary>
        internal static string Salary_Prompt {
            get {
                return ResourceManager.GetString("Salary_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lönespridning:{0, 12:c0}.
        /// </summary>
        internal static string Wage_Dispertion {
            get {
                return ResourceManager.GetString("Wage_Dispertion", resourceCulture);
            }
        }
    }
}
